disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: ''

menu:
- {name: 'Violinist &nbsp | &nbsp Music Creator', path: '.', url: 'index.html'}

social:
- {icon: 'spotify', link: 'https://open.spotify.com/artist/1RbjHDUInleDZjB2xj1bCM'}
- {icon: 'instagram', link: 'https://www.instagram.com/karoliinagabel'}
- {icon: 'apple', link: 'https://music.apple.com/za/artist/karoliina-gabel/1732677238'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCR_MfeH88LUauwntuDxR_dA'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'
sharing_button_prompt: 'Feel free to share!'
related_posts: 'You may also enjoy:'
post_date_prefix: 'Written on'
